# Generated by Django 5.0.2 on 2024-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
