# Generated by Django 5.0.2 on 2024-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_audit', '0002_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_type',
            field=models.CharField(choices=[('user', 'User'), ('customer', 'Customer')], default='Customer', max_length=30, verbose_name='Access'),
        ),
    ]
