# Generated by Django 5.0.2 on 2024-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_audit', '0004_remove_account_slug_remove_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account No'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('INS', 'Insert'), ('UPD', 'Update'), ('DEL', 'Delete')], max_length=15, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('cancel', 'Cancel')], default='Draft', max_length=20, verbose_name='State'),
        ),
    ]
