# Generated by Django 5.0.2 on 2024-02-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_audit', '0005_alter_account_account_no_alter_audit_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
