# Generated by Django 5.0.2 on 2024-02-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_audit', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
